class LocationData {
  final String locality;
  final String mandal;
  final String soilType;
  final int annualRainfall;
  final double roofRunoffCoefficient;
  final double openAreaRunoffCoefficient;
  final String groundwaterDepth;
  final String aquiferDepth;

  LocationData({
    required this.locality,
    required this.mandal,
    required this.soilType,
    required this.annualRainfall,
    required this.roofRunoffCoefficient,
    required this.openAreaRunoffCoefficient,
    required this.groundwaterDepth,
    required this.aquiferDepth,
  });
}

final Map<String, LocationData> locationDataMap = {
  'Marredpally': LocationData(
    locality: 'Marredpally',
    mandal: 'Maredpally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>10',
    aquiferDepth: '100-300',
  ),
  'Secunderabad': LocationData(
    locality: 'Secunderabad',
    mandal: 'Secunderabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>10',
    aquiferDepth: '100-300',
  ),
  'Musheerabad': LocationData(
    locality: 'Musheerabad',
    mandal: 'Musheerabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '5 to 10',
    aquiferDepth: '100-300',
  ),
  'Tirumalagiri': LocationData(
    locality: 'Tirumalagiri',
    mandal: 'Tirumalagiri',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '~19',
    aquiferDepth: '100-300',
  ),
  'Ameerpet': LocationData(
    locality: 'Ameerpet',
    mandal: 'Ameerpet',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Khairatabad': LocationData(
    locality: 'Khairatabad',
    mandal: 'Khairatabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Shaikpet': LocationData(
    locality: 'Shaikpet',
    mandal: 'Shaikpet',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Golconda': LocationData(
    locality: 'Golconda',
    mandal: 'Golconda',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Bahadurpura': LocationData(
    locality: 'Bahadurpura',
    mandal: 'Bahadurpura',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '~1.73',
    aquiferDepth: '100-300',
  ),
  'Charminar': LocationData(
    locality: 'Charminar',
    mandal: 'Charminar',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '5 to 10',
    aquiferDepth: '100-300',
  ),
  'Saidabad': LocationData(
    locality: 'Saidabad',
    mandal: 'Saidabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '5 to 10',
    aquiferDepth: '100-300',
  ),
  'Bandlaguda': LocationData(
    locality: 'Bandlaguda',
    mandal: 'Bandlaguda',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Nampally': LocationData(
    locality: 'Nampally',
    mandal: 'Nampally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Asifnagar': LocationData(
    locality: 'Asifnagar',
    mandal: 'Asifnagar',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Manikonda': LocationData(
    locality: 'Manikonda',
    mandal: 'Shaikpet',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Kukatpally': LocationData(
    locality: 'Kukatpally',
    mandal: 'Quthbullapur',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '~25.90',
    aquiferDepth: '100-300',
  ),
  'Hitec City': LocationData(
    locality: 'Hitec City',
    mandal: 'Serilingampally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>15',
    aquiferDepth: '100-300',
  ),
  'Gachibowli': LocationData(
    locality: 'Gachibowli',
    mandal: 'Serilingampally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>15',
    aquiferDepth: '100-300',
  ),
  'Malakpet': LocationData(
    locality: 'Malakpet',
    mandal: 'Saidabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '5 to 10',
    aquiferDepth: '100-300',
  ),
  'Sanathnagar': LocationData(
    locality: 'Sanathnagar',
    mandal: 'Sanathnagar',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Himayatnagar': LocationData(
    locality: 'Himayatnagar',
    mandal: 'Himayatnagar',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Somajiguda': LocationData(
    locality: 'Somajiguda',
    mandal: 'Ameerpet',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Yousufguda': LocationData(
    locality: 'Yousufguda',
    mandal: 'Khairatabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Lanco Hills': LocationData(
    locality: 'Lanco Hills',
    mandal: 'Shaikpet',
    soilType: 'Red Sandy /Gravely',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Dilsukhnagar': LocationData(
    locality: 'Dilsukhnagar',
    mandal: 'Saroor Nagar',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Jubilee Hills': LocationData(
    locality: 'Jubilee Hills',
    mandal: 'Shaikpet',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Madhapur': LocationData(
    locality: 'Madhapur',
    mandal: 'Serilingampally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>15',
    aquiferDepth: '100-300',
  ),
  'Old City (Bazarghat)': LocationData(
    locality: 'Old City (Bazarghat)',
    mandal: 'Nampally',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '10 to 20',
    aquiferDepth: '100-300',
  ),
  'Kapra': LocationData(
    locality: 'Kapra',
    mandal: 'Kapra',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '>20',
    aquiferDepth: '100-300',
  ),
  'Moosarambagh': LocationData(
    locality: 'Moosarambagh',
    mandal: 'Saidabad',
    soilType: 'Red Sandy /Gravelly',
    annualRainfall: 884,
    roofRunoffCoefficient: 0.80,
    openAreaRunoffCoefficient: 0.30,
    groundwaterDepth: '5 to 10',
    aquiferDepth: '100-300',
  ),
};
